const data = {
  "results": [
    {
      "utc_offset": -18000000,
      "rsvp_limit": 33,
      "headcount": 0,
      "distance": 5.0958337783813,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1486736881000,
      "maybe_rsvp_count": 0,
      "description": "<p>Come join us for a weekly culinary adventure through the countries listed in the Muslim travel ban.<\/p>",
      "event_url": "https:\/\/www.meetup.com\/Resist-Brooklyn\/events\/237609185\/",
      "yes_rsvp_count": 9,
      "duration": 10800000,
      "name": "Resist is the new brunch",
      "id": "237609185",
      "time": 1487696460000,
      "updated": 1487640929000,
      "group": {
        "join_mode": "open",
        "created": 1486182696000,
        "name": "#Resist: Brooklyn",
        "group_lon": -73.959999084473,
        "id": 22222689,
        "urlname": "Resist-Brooklyn",
        "group_lat": 40.680000305176,
        "who": "Members"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "venue": {
        "zip": "10022",
        "country": "us",
        "localized_country_name": "USA",
        "city": "New York",
        "address_1": "145 East 50th Street",
        "address_2": "The Penthouse",
        "lon": -73.972546,
        "phone": "212.888.1220",
        "name": "Upstairs at the Kimberly Hotel",
        "id": 1415301,
        "state": "NY",
        "lat": 40.761998,
        "repinned": false
      },
      "headcount": 0,
      "distance": 1.2359440326691,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1487109017000,
      "maybe_rsvp_count": 0,
      "description": "<p><b>**Please go to the 30th floor and look for the crowd**<\/b> This is not your typical networking event. You never know who will show up to a Cannabis Society Toasty Tuesday. Our events bring a healthy mix of cannabis advocates and professionals from a variety of fields together to network and talk marijuana. The event is 21+ only and business casual, so no sneakers, caps or flip flops please.<\/p> <p>#ToastyTuesday events are completely FREE to enter in order to facilitate all aspects of the cannabis community coming together in a friendly environment <b>but you will need to pay for your own bar tab and food.<\/b><\/p> <p><b>Cannabis Society Membership<\/b> is currently open enrollment for a limited time to Cannabis Society at $75 and includes access to all our high brow events, private events, and unique promotional offers. Apply to become a member here: <a href=\"http:\/\/cansociety.com\/membership\/\" class=\"linkified\">http:\/\/cansociety.com\/membership\/<\/a><\/p> <p>If you're already a member and would like a link to the private membership page for this event please email [masked].<\/p> <p><img src=\"http:\/\/photos1.meetupstatic.com\/photos\/event\/3\/6\/e\/0\/600_458354048.jpeg\" \/><\/p> <p><b>About Toasty Tuesday<\/b><\/p> <p>True innovation often emerges from serendipitous meetings and interactions. Toasty Tuesday's are free professional networking events for the cannabis community. Toasty's began in Boston and New York City and are now expanding west to bring the high end experience of the northeast cannabis industry to the rockies and west coast. We welcome everyone from all backgrounds to attend our events.<\/p> <p><b>About Cannabis Society<\/b><\/p> <p>Cannabis Society is a membership based non-profit social club dedicated to creating sophisticated cannabis experiences. <a href=\"http:\/\/cansociety.com\/\" class=\"linkified\">http:\/\/cansociety.com\/<\/a><\/p> <p><b>About Membership to Cannabis Society<\/b><\/p> <p>Our membership card program connects Cannabis Society members with a curated selection of marijuana lifestyle partners, each offering an exclusive collection of services, products, and experiences created with our members\u2019 discerning tastes and sensibilities in mind. Card Member Benefits are designed to seamlessly integrate our partners\u2019 customized offerings into our members\u2019 personal and business lives.<\/p> <p>Memberships are currently $75 and can be purchased through open enrollment for a very limited time before they double and become invitation only. We are only allowing 200 members at this time. Apply here: <a href=\"http:\/\/cansociety.com\/membership\/\" class=\"linkified\">http:\/\/cansociety.com\/membership\/<\/a><\/p> <p><b>Instagram \/ Twitter \/ Facebook Tips<\/b><\/p> <p>One of the best ways to share our events is to use common hashtags when tweeting, facebooking, or instagramming about the event. Don't forget to take photos and share them with everyone using the hashtags below. #CanSociety #ToastyTuesday #DontDabAlone #DabWithFriends #ToastyNYC<\/p> <p><b>About Empire State NORML<\/b><\/p> <p>Empire State NORML is the New York State Chapter of the National Organization for the Reform of Marijuana Laws. We Empire NORML strives to provide accurate and objective information as it pertains to the responsible adult use of marijuana, industrial hemp, medicinal marijuana and its prohibition status and our reform efforts. <a href=\"http:\/\/esnorml.org\/\" class=\"linkified\">http:\/\/esnorml.org\/<\/a><\/p> <p><img src=\"http:\/\/photos2.meetupstatic.com\/photos\/event\/3\/6\/e\/6\/600_458354054.jpeg\" \/><\/p> <p><b>About Upstairs at the Kimberly Hotel<\/b><\/p> <p>Upstairs stunning penthouse level lounge sits 30 stories high atop the Kimberly Hotel in Midtown Manhattan. The new, 3000 square foot venue features three separate indoor\/outdoor atmospheres, stunning interior design, retractable glass ceilings and walls, ambient heated floors and breathtaking views of the iconic Chrysler Building. Thoughtfully designed to be as elegant and inviting in the winter months as it is sunny and sophisticated in the summer season. Creative cocktails and small plates menu are served nightly. <a href=\"http:\/\/upstairsnyc.com\/\" class=\"linkified\">http:\/\/upstairsnyc.com\/<\/a><\/p> <p><img src=\"http:\/\/photos2.meetupstatic.com\/photos\/event\/3\/6\/f\/3\/600_458354067.jpeg\" \/><\/p> <p><b>About Cannabis Consumption in NYC... <\/b><\/p> <p>Cannabis is not legal to consume in public within New York City so all of our events in NYC will be cannabis free until that changes. We ask that you refrain from using any cannabis products until you have left our event and the venue.<\/p> <p><b>Email List Disclaimer <\/b><\/p> <p>If you RSVP for a Cannabis Society event we add you to our mailing list announcing future events and promotions from our organization. By attending a Cannabis Society event you give us permission to add your email contact information to our mailing list for future contact. For any questions related to our mailing list policy and user privacy please email [masked].<\/p> <p><b>Legal Disclaimer <\/b><\/p> <p>Views or opinions expressed by speakers or sponsors at our local Cannabis Society community events do not necessarily express the opinion or views of the Cannabis Society organization and we do not take responsibility for the views expressed or the actions of speakers or sponsors at our local events. The Cannabis Society does not distribute cannabis.<\/p> <p><b>The Cannabis Society is Growing<\/b> <\/p> <p>Our group has grown by leaps and bounds these past few years and we are proud to announce that the Cannabis Society is going to continue to grow and develop our ecosystem with groundbreaking events centering around medical cannabis, technology, art, and science. We couldn\u2019t do it without our members and we want to thank you for being apart of this growing organization.<\/p> <p><img src=\"http:\/\/photos3.meetupstatic.com\/photos\/event\/3\/7\/0\/1\/600_458354081.jpeg\" \/><\/p>",
      "how_to_find_us": "**Go to the 30th floor and look for the crowd**",
      "event_url": "https:\/\/www.meetup.com\/opencannabis\/events\/237710327\/",
      "yes_rsvp_count": 77,
      "duration": 7200000,
      "name": "Toasty Tuesday Cannabis Networking",
      "id": "237710327",
      "time": 1487718000000,
      "updated": 1487109829000,
      "group": {
        "join_mode": "open",
        "created": 1363479779000,
        "name": "Cannabis Society of New York City",
        "group_lon": -73.98999786377,
        "id": 7649092,
        "urlname": "opencannabis",
        "group_lat": 40.759998321533,
        "who": "Intellectuals"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "venue": {
        "zip": "10001",
        "country": "us",
        "localized_country_name": "USA",
        "city": "New York",
        "address_1": "between 40th and 42nd Streets and 5th and 6th Avenues",
        "lon": -73.983971,
        "phone": "1917 453 1381",
        "name": "Bryant Park",
        "id": 424718,
        "state": "NY",
        "lat": 40.753815,
        "repinned": false
      },
      "headcount": 0,
      "distance": 0.41180267930031,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1486661153000,
      "maybe_rsvp_count": 0,
      "description": "<p>From Snow White to Star Wars, Disney has told generations of children and families that love always triumphs over evil. That's why we find it so strange that Disney's CEO Bob Iger decided to join Trump's Economic Advisory Council. Trump's Economic Advisory Council will help shape economic policy to fulfill Trump's goals, and even help implement them. That means Disney CEO Bob Iger is promising to play a hand in \"building The Wall and making Mexico pay for it,\" and pushing forward Trump's plans to make life harder for immigrants, refugees, and anyone who isn't a millionaire. We're not feeling the love tonight, Disney. We're meeting at Bryant Park and marching up to Disney owned businesses to tell them to leave the Council. We think there's no better day than Valentine's Day to ask Disney to be a hero, stand on the side of love and support refugees, immigrants, and working people by stepping down from Trump's Economic Advisory Council. Uber did it, Disney can too. Meet us at the 6th Avenue and 42nd Street side of park at 6pm, and bring all Disney related signs and slogans (and costumes) to let Disney know love is an open door.<\/p> <p>RSVP here: <a href=\"https:\/\/actionnetwork.org\/events\/resisttrumptuesdays-tell-disney-to-leave-trumps-economic-advisory-council\" class=\"linkified\">https:\/\/actionnetwork.org\/events\/resisttrumptuesdays-tell-disney-to-leave-trumps-economic-advisory-council<\/a><\/p>",
      "how_to_find_us": "Text RESIST to 738674",
      "event_url": "https:\/\/www.meetup.com\/Resist-New-York\/events\/237584681\/",
      "yes_rsvp_count": 6,
      "duration": 7200000,
      "name": "#ResistTrumpTuesdays: Disney Quit The Counsel",
      "id": "237584681",
      "time": 1487718000000,
      "updated": 1487641375000,
      "group": {
        "join_mode": "open",
        "created": 1486182683000,
        "name": "#Resist: New York",
        "group_lon": -73.98999786377,
        "id": 22222677,
        "urlname": "Resist-New-York",
        "group_lat": 40.75,
        "who": "Members"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "venue": {
        "zip": "11222",
        "country": "us",
        "localized_country_name": "USA",
        "city": "Brooklyn",
        "address_1": "136 Milton Street",
        "name": "Greenpoint Church",
        "lon": -73.955798,
        "id": 929467,
        "state": "NY",
        "lat": 40.729306,
        "repinned": false
      },
      "headcount": 0,
      "distance": 2.2959547042847,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1485857303000,
      "maybe_rsvp_count": 0,
      "description": "<p>Update: we have two locations! The meetings are getting so big and we don't want folks turned away so we're planning ahead this time. The address listed in the normal spot, is for those who live in Brooklyn.  <\/p> <p>We've got a more centralized lower Manhattan to accommodate the other boroughs listed below here in the comments. <\/p> <p><b>~~~~~~~~~CWA 1180<br\/><\/b><b>~~~~~~~~~6 Harrison Street <br\/><\/b><b>~~~~~~~~~NYC 10013<\/b><\/p> <p>_________________________________________________________________________<\/p> <p>If You Have Not Already, Please Join Us For Our New Member Orientation \"WHAT IS SOCIALISM and how to talk about it?\" We're going to need it to fight Trump! Learn about our vision of a democratic socialism and our strategy of how to get there! Find out how to get involved in you local Chapter of DSA and on the various committees\/working groups<\/p>",
      "event_url": "https:\/\/www.meetup.com\/nycdsa\/events\/237335788\/",
      "yes_rsvp_count": 141,
      "duration": 5400000,
      "name": "New Member Orientation",
      "id": "237335788",
      "time": 1487719800000,
      "updated": 1487408518000,
      "group": {
        "join_mode": "open",
        "created": 1296094240000,
        "name": "NYC Democratic Socialists of America",
        "group_lon": -74,
        "id": 1773356,
        "urlname": "nycdsa",
        "group_lat": 40.709999084473,
        "who": "Members"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "venue": {
        "zip": "11217",
        "country": "us",
        "localized_country_name": "USA",
        "city": "Brooklyn",
        "address_1": "76 4th Ave",
        "address_2": "(between Bergen and St. Marks)",
        "lon": -73.97988,
        "phone": "718-643-2273",
        "name": "4th Avenue Pub",
        "id": 331301,
        "state": "NY",
        "lat": 40.682247,
        "repinned": false
      },
      "headcount": 0,
      "distance": 4.7209415435791,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1484688995000,
      "maybe_rsvp_count": 0,
      "description": "<p>Join us for the February installment of Drinking Liberally in Downtown Brooklyn.<\/p> <p>\"<i>National Insecurity<\/i>\" - by Justin Krebs<\/p> <p>Trump's national security chief resigns,<br\/>the White House can't get its story straight<br\/>on who knew what and when they knew,<br\/>and Flynn kept getting briefings even after<br\/>the DOJ warned he could be blackmailed.<\/p> <p>Executive orders are stopped by courts,<br\/>but Trump advisers say they can ignore judges,<br\/>as they try to appoint a Supreme Court justice,<br\/>and as ICE detains DACA recipients<br\/>and other folks just for not having ID.<\/p> <p>Israel and China policy change on the fly,<br\/>legions of civil servants resign en masse<br\/>while others go rogue within departments<br\/>that are being led by a Swamp Cabinet<br\/>of kleptocrats, oligarchs, and autocrats.<\/p> <p>Puzder is sunk, Conway is scolded,<br\/>campaign aides were emailing with Russia,<br\/>Trump handles North Korea in public over dinner,<br\/>and finds time to tweet against critics and companies<br\/>to divert attention from his team's impeachable offenses.<\/p> <p>If you're feeling nervous, you're not alone<br\/>as this is all a matter of National Insecurity.<br\/>And for better or for worse it seems<br\/>that Trump may be as insecure as the rest of us.<\/p> <p>Find safety, security, savvy and sanity,<br\/>as you share ideas and a few beers<br\/>at your local progressive social club.<\/p>",
      "event_url": "https:\/\/www.meetup.com\/Drinking-Liberally-Downtown-Brooklyn\/events\/237122713\/",
      "yes_rsvp_count": 11,
      "name": "Drinking Liberally Downtown Brooklyn",
      "id": "hzxdmmywdbcc",
      "time": 1487721600000,
      "updated": 1487631377000,
      "group": {
        "join_mode": "open",
        "created": 1413215774000,
        "name": "Drinking Liberally Downtown Brooklyn",
        "group_lon": -73.980003356934,
        "id": 17593232,
        "urlname": "Drinking-Liberally-Downtown-Brooklyn",
        "group_lat": 40.680000305176,
        "who": "Progressives"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "headcount": 0,
      "distance": 5.0958337783813,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1487637757000,
      "maybe_rsvp_count": 0,
      "description": "<p>Join us the members of <a href=\"https:\/\/www.meetup.com\/Drinking-Liberally-Downtown-Brooklyn\/\">DL Brooklyn<\/a> for its February installment, in solidarity with #Resistance.<\/p> <p>\"<i>National Insecurity<\/i>\" - by Justin Krebs<\/p> <p>Trump's national security chief resigns, <br\/>the White House can't get its story straight <br\/>on who knew what and when they knew, <br\/>and Flynn kept getting briefings even after <br\/>the DOJ warned he could be blackmailed.<\/p> <p>Executive orders are stopped by courts, <br\/>but Trump advisers say they can ignore judges, <br\/>as they try to appoint a Supreme Court justice, <br\/>and as ICE detains DACA recipients <br\/>and other folks just for not having ID.<\/p> <p>Israel and China policy change on the fly, <br\/>legions of civil servants resign en masse <br\/>while others go rogue within departments <br\/>that are being led by a Swamp Cabinet <br\/>of kleptocrats, oligarchs, and autocrats.<\/p> <p>Puzder is sunk, Conway is scolded, <br\/>campaign aides were emailing with Russia, <br\/>Trump handles North Korea in public over dinner, <br\/>and finds time to tweet against critics and companies <br\/>to divert attention from his team's impeachable offenses.<\/p> <p>If you're feeling nervous, you're not alone <br\/>as this is all a matter of National Insecurity. <br\/>And for better or for worse it seems <br\/>that Trump may be as insecure as the rest of us.<\/p> <p>Find safety, security, savvy and sanity, <br\/>as you share ideas and a few beers <br\/>at your local progressive social club.<\/p>",
      "event_url": "https:\/\/www.meetup.com\/Resist-Brooklyn\/events\/237863102\/",
      "yes_rsvp_count": 24,
      "duration": 14400000,
      "name": "Feb. Monthly Meetup - Drinking Liberally Brooklyn and #Resist (In Solidarity)",
      "id": "237863102",
      "time": 1487721600000,
      "updated": 1487637797000,
      "group": {
        "join_mode": "open",
        "created": 1486182696000,
        "name": "#Resist: Brooklyn",
        "group_lon": -73.959999084473,
        "id": 22222689,
        "urlname": "Resist-Brooklyn",
        "group_lat": 40.680000305176,
        "who": "Members"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "venue": {
        "zip": "11217",
        "country": "us",
        "localized_country_name": "USA",
        "city": "Brooklyn",
        "address_1": "647 Fulton St # 2",
        "name": "Bric Arts Media Bklyn",
        "lon": -73.979179,
        "id": 7994612,
        "state": "NY",
        "lat": 40.688354,
        "repinned": false
      },
      "rsvp_limit": 20,
      "headcount": 0,
      "distance": 4.3056015968323,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1487028154000,
      "maybe_rsvp_count": 0,
      "description": "<p>This meetup is my SECOND with Resist. It is under the initiative \"Community Square.\" C-SQ was founded in 2004 with an eventual goal to act as a stand alone non profit, but has since been an information platform for positive and spiritual connecting, discussion group in non traditional ways and environs and better living. We are coming together to educate one another about ways to effectively make our voices be known.<br\/>This meetup is part of a series produced by BRIC Arts. It is one of the leading presenters of free cultural programming in NYC. All of the events we will present with the initiative of Meetup's #Resist in mind will be to compliment them. \"How To Do Social Practice\" is a panel discussion to consider ways artists develop projects, secure funding and make a true impact on our community via social practice.<br\/>It will be moderated by Elizabeth Grady, Program Director, \"A Blade Of Grass.\"<\/p> <p>After, we will ask attendees of OUR group to aid in future meetups for other locations in Brooklyn and possibly elsewhere in (and beyond) New York City. This second portion will only take 15-20 minutes.<\/p>",
      "how_to_find_us": "You will enter the building and go to the front desk. Ask the reception staff for Resist Brooklyn. They will guide you to me, Freedom. You can also text me 646.961.1096 when you arrive!",
      "event_url": "https:\/\/www.meetup.com\/Resist-Brooklyn\/events\/237687964\/",
      "yes_rsvp_count": 7,
      "duration": 9000000,
      "name": "Community Square (2nd Event): How To Do Social Practice",
      "id": "237687964",
      "time": 1487721600000,
      "updated": 1487641272000,
      "group": {
        "join_mode": "open",
        "created": 1486182696000,
        "name": "#Resist: Brooklyn",
        "group_lon": -73.959999084473,
        "id": 22222689,
        "urlname": "Resist-Brooklyn",
        "group_lat": 40.680000305176,
        "who": "Members"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "venue": {
        "country": "us",
        "localized_country_name": "USA",
        "city": "Jackson Heights",
        "address_1": "82-11 37th Ave.",
        "name": "House of Representative Joseph Crowley's Office",
        "lon": -73.883934,
        "id": 25061266,
        "state": "NY",
        "lat": 40.750019,
        "repinned": false
      },
      "headcount": 0,
      "distance": 5.5631065368652,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1487543729000,
      "maybe_rsvp_count": 0,
      "description": "<p>Join us to visit the Jackson Heights office of House of Representative member Joseph Crowley. He is a member of the House Ways and Mean Committee (the Committee which has access to Donald Trump's Tax Returns) and the head of the Queens Democratic Party. We hope to express our concerns about the future of the Democratic party in Queens and beyond and insist that Trump's tax returns be made public.<\/p> <p>We'll be meeting up at 10:00am for a quick lunch and chat at the Jackson House Restaurant [masked]th Ave.) prior to heading to Rep. Crowley's office at 2:00pm.<\/p>",
      "event_url": "https:\/\/www.meetup.com\/Resist-Queens\/events\/237835408\/",
      "yes_rsvp_count": 8,
      "duration": 10800000,
      "name": "Visit to House Representative Joseph Crowley's Office",
      "id": "237835408",
      "time": 1487779200000,
      "updated": 1487693072000,
      "group": {
        "join_mode": "open",
        "created": 1486182698000,
        "name": "#Resist: Queens",
        "group_lon": -73.879997253418,
        "id": 22222690,
        "urlname": "Resist-Queens",
        "group_lat": 40.75,
        "who": "Members"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "venue": {
        "country": "us",
        "localized_country_name": "USA",
        "city": "Jackson Heights",
        "address_1": "82-11 37th Ave.",
        "name": "House Representive Joseph Crowley's Office",
        "lon": -73.883934,
        "id": 25061257,
        "state": "NY",
        "lat": 40.750019,
        "repinned": false
      },
      "headcount": 0,
      "distance": 5.5631065368652,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1487543531000,
      "maybe_rsvp_count": 0,
      "description": "<p>Join us to visit the Jackson Heights office of House of Representative member Joseph Crowley. He is a member of the House Ways and Mean Committee (the Committee which has access to Donald Trump's Tax Returns) and the head of the Queens Democratic Party. We hope to express our concerns about the future of the Democratic party in Queens and beyond and insist that Trump's tax returns be made public.<\/p> <p>We'll be meeting up at 10:00am for a quick lunch and chat at the Jackson House Restaurant [masked]th Ave.) prior to heading to Rep. Crowley's office at 2:00pm.<\/p>",
      "event_url": "https:\/\/www.meetup.com\/NY-Progressives-Meetup\/events\/237835337\/",
      "yes_rsvp_count": 6,
      "duration": 10800000,
      "name": "Visit to House Representative Joseph Crowley's Office",
      "id": "237835337",
      "time": 1487779200000,
      "updated": 1487693159000,
      "group": {
        "join_mode": "open",
        "created": 1479170119000,
        "name": "Queens Democrats Meetup",
        "group_lon": -73.849998474121,
        "id": 21181463,
        "urlname": "NY-Progressives-Meetup",
        "group_lat": 40.680000305176,
        "who": "Members"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "venue": {
        "country": "US",
        "localized_country_name": "USA",
        "city": "New York",
        "address_1": "444 Amsterdam Ave",
        "name": "St. Agnes Library",
        "lon": -73.977211,
        "id": 24034439,
        "lat": 40.78466,
        "repinned": false
      },
      "headcount": 0,
      "distance": 2.4915475845337,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1486586103000,
      "maybe_rsvp_count": 0,
      "description": "<p>This year, 2017, will mark the 100th anniversary of the Russian revolutions. This event had such a huge effect on Russia and the world. It\u2019s a very important period to help understand what\u2019s happening in Russia now, and very important for the national consciousness. However, modern Russia has never properly dealt with the legacy of 1917. On the one hand, the Soviet state that came from the revolution was the one that won the war and whose military and scientific achievements Putin thinks should be venerated. But on the other hand Putin has elevated \u201cstability\u201d to being one of the key tenets of his rule, and as such celebrating a revolution goes against the very grain of his political philosophy.<\/p> <p>Since the outbreak of the Ukraine crisis, there has been much talk of a new Cold War between the West and Russia. Under Vladimir Putin\u2019s leadership, Moscow is widely seen as volatile, belligerent and bent on using military force to get its way. Relations between the West and Russia are certainly bad and dangerous but they are bad and dangerous in new ways; crucial differences which make the current rivalry between Russia, the EU and the US all the more fluid and unpredictable. Unpacking the dynamics of this increasingly strained relationship, we will makes a compelling case for handling Russia with pragmatism and care rather than simply giving into fear.<\/p> <p>In this discussion of top Russian foreign and security policy we explains why the Cold War analogy is misleading and what changes we can expect in U.S-Russia relations under the Trump administration.<\/p>",
      "event_url": "https:\/\/www.meetup.com\/U-S-Russia-Symposium\/events\/237559837\/",
      "yes_rsvp_count": 19,
      "name": "Should We Fear Russia?",
      "id": "237559837",
      "time": 1487800800000,
      "updated": 1486586103000,
      "group": {
        "join_mode": "open",
        "created": 1486585024000,
        "name": "U.S. Russia Relations",
        "group_lon": -73.98999786377,
        "id": 22290436,
        "urlname": "U-S-Russia-Symposium",
        "group_lat": 40.75,
        "who": "Members"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "venue": {
        "zip": "10036",
        "country": "us",
        "localized_country_name": "USA",
        "city": "New York",
        "address_1": "4 West 43rd Street",
        "address_2": "Suite 615",
        "lon": -73.98126,
        "name": "League of Women Voters of New York City",
        "id": 25010228,
        "state": "NY",
        "lat": 40.754272,
        "repinned": false
      },
      "rsvp_limit": 40,
      "headcount": 0,
      "distance": 0.54535716772079,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1485893414000,
      "maybe_rsvp_count": 0,
      "description": "<p>Please join us at our next Open House for new volunteers! We'll be introducing you to the League and volunteer opportunities. This month we are focusing on \u201cAdvocacy in 2017\u201d and will present a panel of LWV members sharing tools, techniques, and tactics to help voters get their voices heard.<\/p> <p>While NYC saw a greater number of voters turnout in 2016 than in 2012, the percentage of eligible voters was only 56.9 percent. We\u2019ve got work to do to help make democracy work and get voters registered and engaged for NYC\u2019s mayoral race.<\/p>",
      "event_url": "https:\/\/www.meetup.com\/LWVNYC\/events\/237347528\/",
      "yes_rsvp_count": 29,
      "duration": 7200000,
      "name": "League Open House: Advocacy and New Volunteers (New Session!)",
      "id": "237347528",
      "time": 1487804400000,
      "updated": 1486482952000,
      "group": {
        "join_mode": "open",
        "created": 1485292268000,
        "name": "League of Women Voters of the City of New York",
        "group_lon": -73.98999786377,
        "id": 22065922,
        "urlname": "LWVNYC",
        "group_lat": 40.759998321533,
        "who": "Members"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "venue": {
        "country": "us",
        "localized_country_name": "USA",
        "city": "New York",
        "address_1": "242 W 30th Street, #806",
        "name": "Beespace NYC",
        "lon": -73.994591,
        "id": 24332590,
        "state": "NY",
        "lat": 40.749104,
        "repinned": false
      },
      "rsvp_limit": 15,
      "headcount": 0,
      "distance": 0.24864043295383,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1460477595000,
      "maybe_rsvp_count": 0,
      "description": "<p><b>PLEASE NOTE: Only RSVP yes if you are actually coming! We want to ensure accurate headcounts and will be taking attendance. If something comes up and you can't make it, be sure to remove your RSVP before the event starts.<\/b><\/p> <p><img src=\"http:\/\/photos2.meetupstatic.com\/photos\/event\/3\/f\/b\/a\/600_445876314.jpeg\" \/><\/p> <p>Hello Heat Seek NYC Volunteers! <\/p> <p>We're having another volunteer meetup. Volunteers with established projects will be hacking on those, and newcomers and non-technical folks are invited to help with our ongoing fundraising research or suggest new projects! <b>Bring your laptops!<\/b><\/p> <p>We encourage new volunteers and those interested in becoming volunteers to join us for the meeting. It's a great opportunity to learn more about our progress and plug in to upcoming volunteer opportunities. Got a great idea for keeping New Yorkers warm this winter? Come and let us know about it! <\/p> <p>We hope to see you there! Call [masked] if you're having trouble getting in.<\/p>",
      "how_to_find_us": "30th Street between 7th and 8th Avenues",
      "event_url": "https:\/\/www.meetup.com\/Heat-Seek-NYC-Volunteers-Meetup\/events\/237769794\/",
      "yes_rsvp_count": 5,
      "duration": 7200000,
      "name": "Heat Seek NYC Volunteer Meetup",
      "id": "lzklslywdbdc",
      "time": 1487804400000,
      "updated": 1460477595000,
      "group": {
        "join_mode": "open",
        "created": 1452702067000,
        "name": "Heat Seek NYC Volunteers Meetup",
        "group_lon": -73.980003356934,
        "id": 19333090,
        "urlname": "Heat-Seek-NYC-Volunteers-Meetup",
        "group_lat": 40.790000915527,
        "who": "Heat Seekers"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "venue": {
        "zip": "10011",
        "country": "us",
        "localized_country_name": "USA",
        "city": "New York",
        "address_1": "208 West 13th Street",
        "address_2": "between 7th & 8th Avenues",
        "lon": -74.001068,
        "phone": "212-620-7310",
        "name": "LGBT Community Center",
        "id": 714998,
        "state": "NY",
        "lat": 40.738144,
        "repinned": false
      },
      "headcount": 0,
      "distance": 1.0055841207504,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1487471726000,
      "maybe_rsvp_count": 0,
      "description": "<p>We weren't able to stop Trump\/Pence before they started.  Every Trump action over has negatively impacted a large group of people. We must stop this fascist trajectory for the sake of humanity and the health of the planet. Come to the meeting where we will discuss the urgency of acting now. Drive Out Trump\/Pence. NO to fascism! <\/p> <p>Join Refuse Fascism to take the message of the new Call from Refuse Fascism, \u201cNO! In the Name of Humanity, We REFUSE to Accept a Fascist America! Drive Out the Trump\/Pence Regime!\u201d <\/p> <p>Our aim is to lead people from protesting the outrages perpetrated by this fascist regime into driving it out. <\/p> <p>\n\n\n Call the Refuse Fascism office &lt;a&gt;[masked]&lt;\/a&gt; for more info.<\/p>",
      "event_url": "https:\/\/www.meetup.com\/Resist-New-York\/events\/237818029\/",
      "yes_rsvp_count": 4,
      "duration": 7200000,
      "name": "Refuse Fascism Organizing Meeting",
      "id": "237818029",
      "time": 1487806200000,
      "updated": 1487641634000,
      "group": {
        "join_mode": "open",
        "created": 1486182683000,
        "name": "#Resist: New York",
        "group_lon": -73.98999786377,
        "id": 22222677,
        "urlname": "Resist-New-York",
        "group_lat": 40.75,
        "who": "Members"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "headcount": 0,
      "distance": 0,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1486422902000,
      "maybe_rsvp_count": 0,
      "description": "<p><b>Speaker<\/b>:  <b><i>Cyrus R. Vance, Jr<\/i><\/b><i><b>.<\/b>,<\/i> District Attorney of New York County<b>.<\/b><\/p> <p>\u2022 About <b>8pm:  <\/b>After the program, we'll <b>gather just outside the room<\/b> and go for an <b>optional dinner<\/b> at a nearby caf\u00e9 or restaurant.<\/p> <p><b>\u2022 Admission free<\/b>.  In addition to signing up here on Meetup, you need to <b>RSVP by email: <\/b>[masked]<\/p> <p><b>------------------<\/b><\/p> <p>RSVPs are also open for our event on Mar. 7:<\/p> <p><a href=\"https:\/\/www.meetup.com\/conservative-137\/events\/237673398\/\"><a href=\"https:\/\/www.meetup.com\/conservative-137\/events\/237673398\/\" class=\"linkified\">https:\/\/www.meetup.com\/conservative-137\/events\/237673398\/<\/a><\/a><\/p> <p><b><a href=\"https:\/\/www.meetup.com\/conservative-137\/events\/237509306\/\"> <\/a><\/b><\/p> <p><b><a href=\"https:\/\/www.meetup.com\/conservative-137\/events\/237509306\/\"><br\/><\/a><\/b><\/p> <p><br\/><b><br\/><\/b><\/p>",
      "event_url": "https:\/\/www.meetup.com\/conservative-137\/events\/237509306\/",
      "yes_rsvp_count": 23,
      "name": "Manhattan DA: Criminal Justice Reform and Sanctuary City",
      "id": "237509306",
      "time": 1487806200000,
      "updated": 1486991636000,
      "group": {
        "join_mode": "open",
        "created": 1142825435000,
        "name": "The New York Conservatives Meetup Group",
        "group_lon": -73.98999786377,
        "id": 229184,
        "urlname": "conservative-137",
        "group_lat": 40.75,
        "who": "Conservatives"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "headcount": 0,
      "distance": 0,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1486439881000,
      "maybe_rsvp_count": 0,
      "description": "<p>This is an invitation to attend and watch a live motion debate as an audience.  This event is sponsored by <b><a href=\"https:\/\/www.motiondebate.com\/\">MotionDebate.com.  <\/a><\/b>Please <b><a href=\"https:\/\/themotiondebatenight.splashthat.com\">click here<\/a><\/b> to sign up for the event.<\/p> <p><br\/><img src=\"https:\/\/a248.e.akamai.net\/secure.meetupstatic.com\/photos\/event\/6\/f\/d\/600_457621789.jpeg\" \/><\/p> <p>Come watch <b><a href=\"https:\/\/www.meetup.com\/NYC-Politics\/members\/80554492\/\">Chuck<\/a> <\/b>and <b><a href=\"https:\/\/www.meetup.com\/NYC-Politics\/members\/191279019\/\">Rob<\/a> <\/b>of the NYCPF debate another team of professional debaters on a motion involving the role of government and public education. The attendees will NOT be participating in the actual debate, as this invitation is offered for those to simply to come and watch a live debate. <\/p> <p><img src=\"https:\/\/a248.e.akamai.net\/secure.meetupstatic.com\/photos\/event\/2\/6\/1\/c\/600_458289756.jpeg\" \/><\/p> <p>The debate format will follow the \"<b><a href=\"https:\/\/en.wikipedia.org\/wiki\/Intelligence_Squared#Debate_format\">Intelligence Squared<\/a><\/b>\" format.<\/p> <p><img src=\"http:\/\/photos4.meetupstatic.com\/photos\/event\/9\/c\/a\/1\/600_458320097.jpeg\" \/><\/p> <p>Once you RSVP, the organizers will send you a link to an external event page to complete the sign up.<\/p> <p>Very limited spots available, offered on a first-come basis.<\/p> <p>-------------------------------<\/p> <p>Event Schedule:<\/p> <p><br\/>6:30pm -- pre-debate intro (beer and cofee offered)<\/p> <p>7:00 to 9:00pm -- motion debate (pro vs. con of the motion)<\/p>",
      "event_url": "https:\/\/www.meetup.com\/NYC-Politics\/events\/237515311\/",
      "yes_rsvp_count": 32,
      "duration": 9000000,
      "name": "Motion Debate: \"Does the government have a duty to educate its citizens?\"",
      "id": "237515311",
      "time": 1487806200000,
      "updated": 1486994048000,
      "group": {
        "join_mode": "open",
        "created": 1386395997000,
        "name": "\"The NYC Political Forum\"",
        "group_lon": -73.98999786377,
        "id": 11370822,
        "urlname": "NYC-Politics",
        "group_lat": 40.75,
        "who": "political thinkers"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "venue": {
        "country": "Un",
        "localized_country_name": "???common.country.un???",
        "city": "New York",
        "address_1": "17 Eastern Parkway",
        "name": "Union Temple of Brooklyn",
        "lon": -73.96801,
        "id": 17412772,
        "lat": 40.673244,
        "repinned": false
      },
      "headcount": 0,
      "distance": 5.4380826950073,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1486819549000,
      "maybe_rsvp_count": 0,
      "description": "<p>Topic: Donald Trump's First 30 Days in Office.<\/p> <p>The primary topic of discussion will be organizing and resisting the Trump administration's agenda. I will also be joined by several experts and community leaders who will speak on the recent executive orders, immigration, health care, and climate change. All of these issues are important to each and every one of us, and it is essential, now more than ever, that we all do our part to stay involved. I hope to see you there. #BrooklynResists<\/p>",
      "event_url": "https:\/\/www.meetup.com\/Resist-Brooklyn\/events\/237632573\/",
      "yes_rsvp_count": 96,
      "duration": 12600000,
      "name": "Congresswoman Yvette D. Clarke Community Town Hall - Trump's First 30 Days",
      "id": "237632573",
      "time": 1487806200000,
      "updated": 1487640532000,
      "group": {
        "join_mode": "open",
        "created": 1486182696000,
        "name": "#Resist: Brooklyn",
        "group_lon": -73.959999084473,
        "id": 22222689,
        "urlname": "Resist-Brooklyn",
        "group_lat": 40.680000305176,
        "who": "Members"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "venue": {
        "country": "us",
        "localized_country_name": "USA",
        "city": "Brooklyn",
        "address_1": "900 Fulton St.",
        "name": "SISTERS",
        "lon": -73.965179,
        "id": 25045755,
        "state": "NY",
        "lat": 40.682873,
        "repinned": false
      },
      "headcount": 0,
      "distance": 4.826566696167,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1486854034000,
      "maybe_rsvp_count": 0,
      "description": "<p>Citizens\u2019 Climate Lobby is a non-profit, non-partisan, grassroots advocacy organization pushing for political action on climate change.<\/p> <p>Come join us for CCL Brooklyn's second chapter meeting, as we get to work pushing for sensible climate action policy at the local, state and national level.<\/p> <p><a href=\"https:\/\/citizensclimatelobby.org\" class=\"linkified\">https:\/\/citizensclimatelobby.org<\/a><\/p>",
      "event_url": "https:\/\/www.meetup.com\/Resist-Brooklyn\/events\/237641820\/",
      "yes_rsvp_count": 11,
      "name": "Citizen's Climate Lobby Brooklyn Meeting",
      "id": "237641820",
      "time": 1487806200000,
      "updated": 1487641069000,
      "group": {
        "join_mode": "open",
        "created": 1486182696000,
        "name": "#Resist: Brooklyn",
        "group_lon": -73.959999084473,
        "id": 22222689,
        "urlname": "Resist-Brooklyn",
        "group_lat": 40.680000305176,
        "who": "Members"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "headcount": 0,
      "distance": 4.911865234375,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1486497736000,
      "maybe_rsvp_count": 0,
      "description": "<p>Welcome to the New Democrats!<\/p> <p>Trump is still in office, preparing to fill the coffers of himself and his rich friends. There's so much work to do for 2018 Mid Term elections. This administration must be stopped!<\/p> <p>In this meeting we will discuss, share ideas and come away with a clear agenda and plan to work towards for 2018. Looking forward to meeting everyone!<\/p> <p>In the meantime, please follow our handle on Twitter:<\/p> <p>@newdems2018<\/p>",
      "event_url": "https:\/\/www.meetup.com\/The-New-Democrats\/events\/237529990\/",
      "yes_rsvp_count": 11,
      "duration": 5400000,
      "name": "The New Democrats - First Meetup!!",
      "id": "237529990",
      "time": 1487806200000,
      "updated": 1486498056000,
      "group": {
        "join_mode": "open",
        "created": 1485673221000,
        "name": "The New Democrats",
        "group_lon": -73.940002441406,
        "id": 22142522,
        "urlname": "The-New-Democrats",
        "group_lat": 40.810001373291,
        "who": "Members"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "venue": {
        "country": "Un",
        "localized_country_name": "???common.country.un???",
        "city": "New York",
        "address_1": "17 Eastern Parkway",
        "name": "Union Temple of Brooklyn",
        "lon": -73.96801,
        "id": 17412772,
        "lat": 40.673244,
        "repinned": false
      },
      "headcount": 0,
      "distance": 5.4380826950073,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1487022168000,
      "maybe_rsvp_count": 0,
      "description": "<p>Yvette Clark is holding an in-person Town Hall at the Union Temple at 17 Eastern Parkway, in Brooklyn. Topics will include \"the Trump administration's threat to health care\" among others. Please let us know if you can attend, and don't forget an Indivisible sign!<\/p>",
      "event_url": "https:\/\/www.meetup.com\/Indivisible-Action-Planning-NYC\/events\/237685635\/",
      "yes_rsvp_count": 3,
      "duration": 7200000,
      "name": "Congresswoman Yvette Clark (District 9) Town Hall",
      "id": "237685635",
      "time": 1487808000000,
      "updated": 1487022217000,
      "group": {
        "join_mode": "open",
        "created": 1486864178000,
        "name": "Indivisible Action Planning NYC",
        "group_lon": -73.98999786377,
        "id": 22343267,
        "urlname": "Indivisible-Action-Planning-NYC",
        "group_lat": 40.75,
        "who": "Members"
      },
      "status": "upcoming"
    },
    {
      "utc_offset": -18000000,
      "headcount": 0,
      "distance": 0,
      "visibility": "public",
      "waitlist_count": 0,
      "created": 1485637303000,
      "maybe_rsvp_count": 0,
      "description": "<p>The Trump Administration presents unique challenges to our constitutional rights. I will spend the evening presenting on two of our most important constitutional rights: freedom of speech under the First Amendment and right to privacy under the Fourth Amendment. <\/p> <p>Specifically, we will focus on what constitutes constitutionally protected speech and when it is necessary to obtain a permit to protest. We will also focus on the right to be free from unreasonable searches and seizures.<\/p> <p>My presentation will provide a mix of theory and history. We\u2019ll discuss the origin of these rights in our Constitution as well as their real life application in today\u2019s world. <\/p> <p>This is the first of many lessons on the US Constitution. Don\u2019t worry. We will cover it all, including every single one of our rights in the Bill of Rights. I hope to see many of you there. And please stay tuned for more event announcements in the coming days\/weeks. Best, Danny <\/p> <p>P.S. The information presented at this meeting is for educational purposes only and not for the purpose of providing legal advice. I, Daniel Miller, DO NOT represent you or any attendee of this presentation in any legal matter. An attorney-client relationship has not been created by attendance at this meeting. You should contact your attorney to obtain advice with respect to any particular issue or problem.<\/p>",
      "event_url": "https:\/\/www.meetup.com\/The-Society-for-Constitutional-Protection\/events\/237274870\/",
      "yes_rsvp_count": 20,
      "duration": 7200000,
      "name": "Con Law for the Resistance",
      "id": "237274870",
      "time": 1487809800000,
      "updated": 1487611012000,
      "group": {
        "join_mode": "open",
        "created": 1480975379000,
        "name": "The Society for Constitutional Protection",
        "group_lon": -73.98999786377,
        "id": 21471196,
        "urlname": "The-Society-for-Constitutional-Protection",
        "group_lat": 40.75,
        "who": "Members"
      },
      "status": "upcoming"
    }
  ],
  "meta": {
    "next": "https:\/\/api.meetup.com\/2\/open_events?zip=10001&and_text=False&offset=1&sign=True&format=json&limited_events=False&photo-host=public&page=20&radius=25.0&category=13&key=61e1b239102b621e5721214ea78&desc=False&status=upcoming",
    "method": "OpenEvents",
    "total_count": 104,
    "link": "https:\/\/api.meetup.com\/2\/open_events",
    "count": 20,
    "description": "Searches for recent and upcoming public events hosted by Meetup groups. Its search window  is the past one month through the next three months, and is subject to change. Open Events is optimized to search for current events by location, category, topic, or text, and only lists Meetups that have **3 or more RSVPs**. The number or results returned with each request is not guaranteed to be the same as the page size due to secondary filtering. If you're looking for a particular event or events within a particular group, use the standard [Events](\/meetup_api\/docs\/2\/events\/) method.",
    "lon": "None",
    "title": "Meetup Open Events v2",
    "url": "https:\/\/api.meetup.com\/2\/open_events?zip=10001&and_text=False&offset=0&sign=True&format=json&limited_events=False&photo-host=public&page=20&radius=25.0&category=13&key=61e1b239102b621e5721214ea78&desc=False&status=upcoming",
    "signed_url": "https:\/\/api.meetup.com\/2\/open_events?zip=10001&and_text=False&offset=0&format=json&limited_events=False&photo-host=public&page=20&radius=25.0&category=13&desc=False&status=upcoming&sig_id=222417325&sig=e0524dc14da58206e90d21584240377c1e467ae2",
    "id": "",
    "updated": 1487694375010,
    "lat": "None"
  }
};

export default data;
